language: python
python:
- 2.7

env:
  global:
  - secure: "UxpVOfQ9oePIcgRqsFzuVvpcng/syX6snuqw01XjK/3dWwyjhehBL17Yfzsn8NAgsiEdJ7SiTOhb3cfiHNHNX0mzfojPtvcFcGDmHGfH5nIufsGubeck6CErKHFT0uAhJywfPSgi53n0RteiIJAKc0bzaYzoMRG7RUPsvk3HRnE="

before_install:
- sudo add-apt-repository -y -r ppa:ubuntugis/ppa
- sudo apt-get update
- sudo apt-get install -y --force-yes postgresql-9.1-postgis=1.5.3-2 postgis=1.5.3-2 apache2 cgi-mapserver
- sudo -u postgres createdb -E UTF8 -T template0 c2cgeoportal_test
- sudo -u postgres psql -q -d c2cgeoportal_test -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
- sudo -u postgres psql -q -d c2cgeoportal_test -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql
- sudo -u postgres createuser www-data --no-superuser --no-createdb --no-createrole
- sudo -u postgres psql -q -d c2cgeoportal_test -f travis/db.sql
- pip install urllib3
- sudo apache2ctl graceful

install:
- python bootstrap.py --version 1.5.2 --distribute --download-base http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/ --setup-source http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/distribute_setup.py
- ./buildout/bin/buildout -c buildout_travis.cfg

before_script:
- cd doc
- virtualenv --no-site-packages --distribute env
- source env/bin/activate
- pip install -r requirements.txt
- cd -

script: 
- ./travis/doc.sh
- find c2cgeoportal/*.py c2cgeoportal/lib c2cgeoportal/scripts c2cgeoportal/views -name \*.py | xargs ./buildout/bin/flake8 --ignore=E712 --max-complexity=20 --max-line-length=100
- find c2cgeoportal/*.py c2cgeoportal/tests -name \*.py | xargs ./buildout/bin/flake8 --ignore=E501
- buildout/bin/pcreate -s c2cgeoportal_create /tmp/test package=test srid=21781 mobile_application_title="Mobile App"
- buildout/bin/pcreate -s c2cgeoportal_update /tmp/test package=test
- buildout/bin/migrate version /tmp/test/test/CONST_migration/
- rm -rf /tmp/test
- buildout/bin/python setup.py nosetests

after_success:
- travis/deploy.sh
- pip install coveralls
- coveralls

notifications:
  email:
    recipients:
    - c2cgeoportal@camptocamp.com
